#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CarControlAndroid.Resource", IsApplication=true)]

namespace CarControlAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			EdiabasLibAndroid.Resource.String.library_name = CarControlAndroid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int tab_bg_selected = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int tab_bg_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int tab_bg_unselected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int tab_divider = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int tab_text_selector = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002a
			public const int ListText1 = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int ListText2 = 2131099691;
			
			// aapt resource value: 0x7f060029
			public const int buttonConnect = 2131099689;
			
			// aapt resource value: 0x7f060024
			public const int button_adapter_config_can_100 = 2131099684;
			
			// aapt resource value: 0x7f060023
			public const int button_adapter_config_can_500 = 2131099683;
			
			// aapt resource value: 0x7f060025
			public const int button_adapter_config_can_off = 2131099685;
			
			// aapt resource value: 0x7f060007
			public const int button_axis_down = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int button_axis_up = 2131099656;
			
			// aapt resource value: 0x7f060013
			public const int button_rot_irregular_active = 2131099667;
			
			// aapt resource value: 0x7f060004
			public const int button_scan = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int button_uneven_running_active = 2131099663;
			
			// aapt resource value: 0x7f06002f
			public const int menu_enable_log = 2131099695;
			
			// aapt resource value: 0x7f06002e
			public const int menu_scan = 2131099694;
			
			// aapt resource value: 0x7f060003
			public const int new_devices = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int paired_devices = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int resultListAxis = 2131099654;
			
			// aapt resource value: 0x7f060021
			public const int scrollViewAdapterConfig = 2131099681;
			
			// aapt resource value: 0x7f060018
			public const int scrollViewTextCccNav = 2131099672;
			
			// aapt resource value: 0x7f06001e
			public const int scrollViewTextErrors = 2131099678;
			
			// aapt resource value: 0x7f06001b
			public const int scrollViewTextIhk = 2131099675;
			
			// aapt resource value: 0x7f06000a
			public const int scrollViewTextMotor = 2131099658;
			
			// aapt resource value: 0x7f060015
			public const int scrollViewTextMotorPm = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int scrollViewTextMotorRotIrregular = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int scrollViewTextMotorUnevenRunning = 2131099661;
			
			// aapt resource value: 0x7f060027
			public const int scrollViewTextTest = 2131099687;
			
			// aapt resource value: 0x7f060020
			public const int tabAdapterConfig = 2131099680;
			
			// aapt resource value: 0x7f060005
			public const int tabAxis = 2131099653;
			
			// aapt resource value: 0x7f060017
			public const int tabCccNav = 2131099671;
			
			// aapt resource value: 0x7f06001d
			public const int tabErrors = 2131099677;
			
			// aapt resource value: 0x7f06001a
			public const int tabIhk = 2131099674;
			
			// aapt resource value: 0x7f060009
			public const int tabMotor = 2131099657;
			
			// aapt resource value: 0x7f060014
			public const int tabMotorPm = 2131099668;
			
			// aapt resource value: 0x7f060010
			public const int tabMotorRotIrregular = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public const int tabMotorUnevenRunning = 2131099660;
			
			// aapt resource value: 0x7f060026
			public const int tabTest = 2131099686;
			
			// aapt resource value: 0x7f06002c
			public const int tabsLayout = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int tabsText = 2131099693;
			
			// aapt resource value: 0x7f060022
			public const int textViewResultAdapterConfig = 2131099682;
			
			// aapt resource value: 0x7f060019
			public const int textViewResultCccNav = 2131099673;
			
			// aapt resource value: 0x7f06001f
			public const int textViewResultErrors = 2131099679;
			
			// aapt resource value: 0x7f06001c
			public const int textViewResultIhk = 2131099676;
			
			// aapt resource value: 0x7f06000b
			public const int textViewResultMotor = 2131099659;
			
			// aapt resource value: 0x7f060016
			public const int textViewResultMotorPm = 2131099670;
			
			// aapt resource value: 0x7f060012
			public const int textViewResultMotorRotIrregular = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int textViewResultMotorUnevenRunning = 2131099662;
			
			// aapt resource value: 0x7f060028
			public const int textViewResultTest = 2131099688;
			
			// aapt resource value: 0x7f060002
			public const int title_new_devices = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int title_paired_devices = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int device_list = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int device_name = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int result_list = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int tabs_bg = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int option_menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040074
			public const int adapter_config_error = 2130968692;
			
			// aapt resource value: 0x7f040075
			public const int adapter_config_ok = 2130968693;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int axis_mode_conveyor = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int axis_mode_garage = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int axis_mode_normal = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int axis_mode_transport = 2130968588;
			
			// aapt resource value: 0x7f040005
			public const int bt_not_available = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int bt_not_enabled_leaving = 2130968580;
			
			// aapt resource value: 0x7f040072
			public const int button_adapter_config_can_100 = 2130968690;
			
			// aapt resource value: 0x7f040071
			public const int button_adapter_config_can_500 = 2130968689;
			
			// aapt resource value: 0x7f040073
			public const int button_adapter_config_can_off = 2130968691;
			
			// aapt resource value: 0x7f040008
			public const int button_axis_down = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int button_axis_up = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int button_connected = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int button_disconnected = 2130968579;
			
			// aapt resource value: 0x7f040032
			public const int button_rot_irregular_off = 2130968626;
			
			// aapt resource value: 0x7f040031
			public const int button_rot_irregular_on = 2130968625;
			
			// aapt resource value: 0x7f04007d
			public const int button_scan = 2130968701;
			
			// aapt resource value: 0x7f04002b
			public const int button_uneven_running_off = 2130968619;
			
			// aapt resource value: 0x7f04002a
			public const int button_uneven_running_on = 2130968618;
			
			// aapt resource value: 0x7f040057
			public const int errorNameACSM = 2130968663;
			
			// aapt resource value: 0x7f040058
			public const int errorNameAHM = 2130968664;
			
			// aapt resource value: 0x7f040059
			public const int errorNameCAS = 2130968665;
			
			// aapt resource value: 0x7f04005a
			public const int errorNameCCCA = 2130968666;
			
			// aapt resource value: 0x7f04005b
			public const int errorNameCCCANT = 2130968667;
			
			// aapt resource value: 0x7f04005c
			public const int errorNameCCCASK = 2130968668;
			
			// aapt resource value: 0x7f04005d
			public const int errorNameCCCBO = 2130968669;
			
			// aapt resource value: 0x7f04005e
			public const int errorNameCCCGW = 2130968670;
			
			// aapt resource value: 0x7f04005f
			public const int errorNameCDC = 2130968671;
			
			// aapt resource value: 0x7f040060
			public const int errorNameCID = 2130968672;
			
			// aapt resource value: 0x7f040061
			public const int errorNameCON = 2130968673;
			
			// aapt resource value: 0x7f040062
			public const int errorNameDDE = 2130968674;
			
			// aapt resource value: 0x7f040063
			public const int errorNameDSC = 2130968675;
			
			// aapt resource value: 0x7f040064
			public const int errorNameEHC = 2130968676;
			
			// aapt resource value: 0x7f040065
			public const int errorNameEKPS = 2130968677;
			
			// aapt resource value: 0x7f040066
			public const int errorNameIHK = 2130968678;
			
			// aapt resource value: 0x7f040067
			public const int errorNameKBM = 2130968679;
			
			// aapt resource value: 0x7f040068
			public const int errorNameKGM = 2130968680;
			
			// aapt resource value: 0x7f040069
			public const int errorNameKOMBI = 2130968681;
			
			// aapt resource value: 0x7f04006a
			public const int errorNameLM = 2130968682;
			
			// aapt resource value: 0x7f04006b
			public const int errorNamePDC = 2130968683;
			
			// aapt resource value: 0x7f04006c
			public const int errorNameRLS = 2130968684;
			
			// aapt resource value: 0x7f04006d
			public const int errorNameSZL = 2130968685;
			
			// aapt resource value: 0x7f04006e
			public const int errorNameSZM = 2130968686;
			
			// aapt resource value: 0x7f04006f
			public const int errorNameTCU = 2130968687;
			
			// aapt resource value: 0x7f040055
			public const int error_no_error = 2130968661;
			
			// aapt resource value: 0x7f040056
			public const int error_no_response = 2130968662;
			
			// aapt resource value: 0x7f040010
			public const int label_axis_bat_volt = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int label_axis_left = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int label_axis_mode = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int label_axis_right = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int label_axis_speed = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int label_axis_valve_state = 2130968594;
			
			// aapt resource value: 0x7f040042
			public const int label_ccc_nav_almanach = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int label_ccc_nav_gps_date_time = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int label_ccc_nav_hip_driver = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int label_ccc_nav_pos_height = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int label_ccc_nav_pos_lat = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int label_ccc_nav_pos_long = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int label_ccc_nav_pos_type = 2130968648;
			
			// aapt resource value: 0x7f040049
			public const int label_ccc_nav_res_horz = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int label_ccc_nav_res_pos = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int label_ccc_nav_res_vert = 2130968651;
			
			// aapt resource value: 0x7f04004c
			public const int label_ccc_nav_speed = 2130968652;
			
			// aapt resource value: 0x7f04004e
			public const int label_ihk_heat_ex_setpoint = 2130968654;
			
			// aapt resource value: 0x7f04004f
			public const int label_ihk_heat_ex_temp = 2130968655;
			
			// aapt resource value: 0x7f040050
			public const int label_ihk_in_temp = 2130968656;
			
			// aapt resource value: 0x7f040051
			public const int label_ihk_in_temp_delay = 2130968657;
			
			// aapt resource value: 0x7f040052
			public const int label_ihk_out_temp = 2130968658;
			
			// aapt resource value: 0x7f040053
			public const int label_ihk_setpoint = 2130968659;
			
			// aapt resource value: 0x7f040014
			public const int label_motor_air_mass = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int label_motor_air_mass_act = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int label_motor_air_mass_set = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int label_motor_ambient_press = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int label_motor_ambient_temp = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int label_motor_bat_voltage = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int label_motor_boost_press_act = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int label_motor_boost_press_set = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int label_motor_exhaust_press = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int label_motor_fuel_temp = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int label_motor_intake_air_temp = 2130968606;
			
			// aapt resource value: 0x7f040023
			public const int label_motor_oil_press_switch = 2130968611;
			
			// aapt resource value: 0x7f04001f
			public const int label_motor_part_filt_dist_since_regen = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int label_motor_part_filt_request = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int label_motor_part_filt_status = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int label_motor_part_filt_unblocked = 2130968610;
			
			// aapt resource value: 0x7f040038
			public const int label_motor_pm_bat_cap = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int label_motor_pm_cal_events = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int label_motor_pm_day1 = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int label_motor_pm_season_temp = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int label_motor_pm_soc_fit = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int label_motor_pm_soc_percent = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int label_motor_pm_soc_q = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int label_motor_pm_soh = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int label_motor_pm_start_cap = 2130968640;
			
			// aapt resource value: 0x7f04002c
			public const int label_motor_quant_corr_c1 = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int label_motor_quant_corr_c2 = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int label_motor_quant_corr_c3 = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int label_motor_quant_corr_c4 = 2130968623;
			
			// aapt resource value: 0x7f040024
			public const int label_motor_rail_press_act = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int label_motor_rail_press_set = 2130968613;
			
			// aapt resource value: 0x7f040033
			public const int label_motor_rpm_c1 = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int label_motor_rpm_c2 = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int label_motor_rpm_c3 = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int label_motor_rpm_c4 = 2130968630;
			
			// aapt resource value: 0x7f040026
			public const int label_motor_temp = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int label_motor_temp_before_cat = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int label_motor_temp_before_filter = 2130968616;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f04007e
			public const int menu_connect = 2130968702;
			
			// aapt resource value: 0x7f040080
			public const int menu_enable_log_off = 2130968704;
			
			// aapt resource value: 0x7f04007f
			public const int menu_enable_log_on = 2130968703;
			
			// aapt resource value: 0x7f04007a
			public const int none_found = 2130968698;
			
			// aapt resource value: 0x7f040079
			public const int none_paired = 2130968697;
			
			// aapt resource value: 0x7f040077
			public const int scanning = 2130968695;
			
			// aapt resource value: 0x7f040078
			public const int select_device = 2130968696;
			
			// aapt resource value: 0x7f040070
			public const int tab_adapter_config = 2130968688;
			
			// aapt resource value: 0x7f040006
			public const int tab_axis = 2130968582;
			
			// aapt resource value: 0x7f040041
			public const int tab_ccc_nav = 2130968641;
			
			// aapt resource value: 0x7f040054
			public const int tab_errors = 2130968660;
			
			// aapt resource value: 0x7f04004d
			public const int tab_ihk = 2130968653;
			
			// aapt resource value: 0x7f040013
			public const int tab_motor = 2130968595;
			
			// aapt resource value: 0x7f040037
			public const int tab_motor_pm = 2130968631;
			
			// aapt resource value: 0x7f040030
			public const int tab_motor_rot_irregular = 2130968624;
			
			// aapt resource value: 0x7f040029
			public const int tab_motor_uneven_running = 2130968617;
			
			// aapt resource value: 0x7f040076
			public const int tab_test = 2130968694;
			
			// aapt resource value: 0x7f04007c
			public const int title_other_devices = 2130968700;
			
			// aapt resource value: 0x7f04007b
			public const int title_paired_devices = 2130968699;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
