//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsdzClientLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PsdzClientLibrary.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application restart required. ähnelt.
        /// </summary>
        internal static string AppRestartRequired {
            get {
                return ResourceManager.GetString("AppRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup data restored. ähnelt.
        /// </summary>
        internal static string BackupDataRestored {
            get {
                return ResourceManager.GetString("BackupDataRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battery voltage: {0:0.00}V ähnelt.
        /// </summary>
        internal static string BatteryVoltage {
            get {
                return ResourceManager.GetString("BatteryVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error:
        ///The battery voltage {0:0.00}V is out of valid range:
        ///{1:0.00}V - {2:0.00}V.
        ///Please connect a certified charger for the whole coding session.
        ///Do you want to retry the operation? ähnelt.
        /// </summary>
        internal static string BatteryVoltageError {
            get {
                return ResourceManager.GetString("BatteryVoltageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information:
        ///The battery voltage {0:0.00}V is inside the valid range:
        ///{1:0.00}V - {2:0.00}V.
        ///Please connect a certified charger for the whole coding session. ähnelt.
        /// </summary>
        internal static string BatteryVoltageInfo {
            get {
                return ResourceManager.GetString("BatteryVoltageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battery voltage reading failed. ähnelt.
        /// </summary>
        internal static string BatteryVoltageReadError {
            get {
                return ResourceManager.GetString("BatteryVoltageReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning:
        ///The battery voltage {0:0.00}V is out of valid range:
        ///{1:0.00}V - {2:0.00}V.
        ///Please connect a certified charger for the whole coding session. ähnelt.
        /// </summary>
        internal static string BatteryVoltageWarn {
            get {
                return ResourceManager.GetString("BatteryVoltageWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Certifiates for secure connection missing. ähnelt.
        /// </summary>
        internal static string CertificatesNotPresent {
            get {
                return ResourceManager.GetString("CertificatesNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Context not found. ähnelt.
        /// </summary>
        internal static string ContextMissing {
            get {
                return ResourceManager.GetString("ContextMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creating backup path failed. ähnelt.
        /// </summary>
        internal static string CreateBackupPathFailed {
            get {
                return ResourceManager.GetString("CreateBackupPathFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database version: {0}, date: {1} ähnelt.
        /// </summary>
        internal static string DbInfo {
            get {
                return ResourceManager.GetString("DbInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detecting installed ECUs ... ähnelt.
        /// </summary>
        internal static string DetectingInstalledEcus {
            get {
                return ResourceManager.GetString("DetectingInstalledEcus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detecting installed ECUs failed. ähnelt.
        /// </summary>
        internal static string DetectInstalledEcusFailed {
            get {
                return ResourceManager.GetString("DetectInstalledEcusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: {0} ähnelt.
        /// </summary>
        internal static string ExceptionMsg {
            get {
                return ResourceManager.GetString("ExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Executing backup TAL ... ähnelt.
        /// </summary>
        internal static string ExecutingBackupTal {
            get {
                return ResourceManager.GetString("ExecutingBackupTal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Executing restore TAL ... ähnelt.
        /// </summary>
        internal static string ExecutingRestoreTal {
            get {
                return ResourceManager.GetString("ExecutingRestoreTal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Executing TAL ... ähnelt.
        /// </summary>
        internal static string ExecutingTal {
            get {
                return ResourceManager.GetString("ExecutingTal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Executing operation ... ähnelt.
        /// </summary>
        internal static string ExecutingVehicleFunc {
            get {
                return ResourceManager.GetString("ExecutingVehicleFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation finished. ähnelt.
        /// </summary>
        internal static string ExecutingVehicleFuncFinished {
            get {
                return ResourceManager.GetString("ExecutingVehicleFuncFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FA backup write failed. ähnelt.
        /// </summary>
        internal static string FaBackupWriteFailed {
            get {
                return ResourceManager.GetString("FaBackupWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FA backup written. ähnelt.
        /// </summary>
        internal static string FaBackupWritten {
            get {
                return ResourceManager.GetString("FaBackupWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FA write failed. ähnelt.
        /// </summary>
        internal static string FaWriteFailed {
            get {
                return ResourceManager.GetString("FaWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FA written. ähnelt.
        /// </summary>
        internal static string FaWritten {
            get {
                return ResourceManager.GetString("FaWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generating vehicle info files failed. ähnelt.
        /// </summary>
        internal static string GenerateInfoFilesFailed {
            get {
                return ResourceManager.GetString("GenerateInfoFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generating vehicle info files. ähnelt.
        /// </summary>
        internal static string GeneratingInfoFiles {
            get {
                return ResourceManager.GetString("GeneratingInfoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service host started. ähnelt.
        /// </summary>
        internal static string HostStarted {
            get {
                return ResourceManager.GetString("HostStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting host failed. ähnelt.
        /// </summary>
        internal static string HostStartFailed {
            get {
                return ResourceManager.GetString("HostStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting service host ... ähnelt.
        /// </summary>
        internal static string HostStarting {
            get {
                return ResourceManager.GetString("HostStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service host stopped. ähnelt.
        /// </summary>
        internal static string HostStopped {
            get {
                return ResourceManager.GetString("HostStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopping service host ... ähnelt.
        /// </summary>
        internal static string HostStopping {
            get {
                return ResourceManager.GetString("HostStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A hardware replacement operation is active.
        ///Do you want to continue the last hardware replace operation? ähnelt.
        /// </summary>
        internal static string HwReplaceContinue {
            get {
                return ResourceManager.GetString("HwReplaceContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ILevel backup failed. ähnelt.
        /// </summary>
        internal static string ILevelBackupFailed {
            get {
                return ResourceManager.GetString("ILevelBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ILevel backup updated. ähnelt.
        /// </summary>
        internal static string ILevelBackupUpdated {
            get {
                return ResourceManager.GetString("ILevelBackupUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ILevel updated. ähnelt.
        /// </summary>
        internal static string ILevelUpdated {
            get {
                return ResourceManager.GetString("ILevelUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ILevel update failed. ähnelt.
        /// </summary>
        internal static string ILevelUpdateFailed {
            get {
                return ResourceManager.GetString("ILevelUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detected Ncd failures. ähnelt.
        /// </summary>
        internal static string NcdFailures {
            get {
                return ResourceManager.GetString("NcdFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NCD online calculation required.
        ///Probably you have selected a chargable option. ähnelt.
        /// </summary>
        internal static string NcdOnlineCalculation {
            get {
                return ResourceManager.GetString("NcdOnlineCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NCD request file missing. ähnelt.
        /// </summary>
        internal static string NoNcdRequestFile {
            get {
                return ResourceManager.GetString("NoNcdRequestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No target ILevel present. ähnelt.
        /// </summary>
        internal static string NoTargetILevel {
            get {
                return ResourceManager.GetString("NoTargetILevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not valid license for vehicle present. ähnelt.
        /// </summary>
        internal static string NoVehiceLicense {
            get {
                return ResourceManager.GetString("NoVehiceLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PIA master updated. ähnelt.
        /// </summary>
        internal static string PiaMasterUpdated {
            get {
                return ResourceManager.GetString("PiaMasterUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PIA master update failed. ähnelt.
        /// </summary>
        internal static string PiaMasterUpdateFailed {
            get {
                return ResourceManager.GetString("PiaMasterUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check programming counter failed. ähnelt.
        /// </summary>
        internal static string PrgCounterCheckFailed {
            get {
                return ResourceManager.GetString("PrgCounterCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programming counters: {0} ähnelt.
        /// </summary>
        internal static string PrgCounters {
            get {
                return ResourceManager.GetString("PrgCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reading FA failed. ähnelt.
        /// </summary>
        internal static string ReadFaFailed {
            get {
                return ResourceManager.GetString("ReadFaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reading ILevel failed. ähnelt.
        /// </summary>
        internal static string ReadILevelFailed {
            get {
                return ResourceManager.GetString("ReadILevelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reading VIN failed. ähnelt.
        /// </summary>
        internal static string ReadVinFailed {
            get {
                return ResourceManager.GetString("ReadVinFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requesting ECU context failed. ähnelt.
        /// </summary>
        internal static string RequestEcuContextFailed {
            get {
                return ResourceManager.GetString("RequestEcuContextFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requesting planned development failed. ähnelt.
        /// </summary>
        internal static string RequestedFlashSetupFailed {
            get {
                return ResourceManager.GetString("RequestedFlashSetupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requesting planned construction failed. ähnelt.
        /// </summary>
        internal static string RequestedPlannedConstructionFailed {
            get {
                return ResourceManager.GetString("RequestedPlannedConstructionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requesting ECU context ... ähnelt.
        /// </summary>
        internal static string RequestingEcuContext {
            get {
                return ResourceManager.GetString("RequestingEcuContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detected {0} software failures. ähnelt.
        /// </summary>
        internal static string SoftwareFailures {
            get {
                return ResourceManager.GetString("SoftwareFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SWI Version: {0} ähnelt.
        /// </summary>
        internal static string SwiVersion {
            get {
                return ResourceManager.GetString("SwiVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requesting SWT action ... ähnelt.
        /// </summary>
        internal static string SwtAction {
            get {
                return ResourceManager.GetString("SwtAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SWT actions: {0} ähnelt.
        /// </summary>
        internal static string SwtActionCount {
            get {
                return ResourceManager.GetString("SwtActionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Request SWT action failed. ähnelt.
        /// </summary>
        internal static string SwtActionFailed {
            get {
                return ResourceManager.GetString("SwtActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The FA has changed since the last backup.
        ///Do you want to restore the settings of the last backup? ähnelt.
        /// </summary>
        internal static string TalBackupFaChanged {
            get {
                return ResourceManager.GetString("TalBackupFaChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generating backup TAL ... ähnelt.
        /// </summary>
        internal static string TalBackupGenerating {
            get {
                return ResourceManager.GetString("TalBackupGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup TAL generation failed. ähnelt.
        /// </summary>
        internal static string TalBackupGenerationFailed {
            get {
                return ResourceManager.GetString("TalBackupGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to disable all flash operations for this session? ähnelt.
        /// </summary>
        internal static string TalDisableFlash {
            get {
                return ResourceManager.GetString("TalDisableFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to execute the main TAL again (slow)? ähnelt.
        /// </summary>
        internal static string TalExecuteAgain {
            get {
                return ResourceManager.GetString("TalExecuteAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TAL execution finished with errors. ähnelt.
        /// </summary>
        internal static string TalExecuteError {
            get {
                return ResourceManager.GetString("TalExecuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problems have occured in the preparation phase.
        ///No liability in case of failure or problems after coding!
        ///Do you still want to continue with TAL execution? ähnelt.
        /// </summary>
        internal static string TalExecuteErrorContinue {
            get {
                return ResourceManager.GetString("TalExecuteErrorContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The last time the TAL execution has been skipped. ähnelt.
        /// </summary>
        internal static string TalExecuteLastSkipped {
            get {
                return ResourceManager.GetString("TalExecuteLastSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The last time the TAL has been executed successfully. ähnelt.
        /// </summary>
        internal static string TalExecuteLastSuccess {
            get {
                return ResourceManager.GetString("TalExecuteLastSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TAL execution finished ok. ähnelt.
        /// </summary>
        internal static string TalExecuteOk {
            get {
                return ResourceManager.GetString("TalExecuteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preparation has been finshied successfully.
        ///No liability in case of failure or problems after coding!
        ///Do you want to continue with TAL execution? ähnelt.
        /// </summary>
        internal static string TalExecuteOkContinue {
            get {
                return ResourceManager.GetString("TalExecuteOkContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TAL execution finished with warnings. ähnelt.
        /// </summary>
        internal static string TalExecuteWarning {
            get {
                return ResourceManager.GetString("TalExecuteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TAL execution failed.
        ///Do you want to retry TAL execution with the same settings later? ähnelt.
        /// </summary>
        internal static string TalExecutionFailMessage {
            get {
                return ResourceManager.GetString("TalExecutionFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Make sure that the ignition is switched on, the motor is stopped and a certified charger is connected to the vehicle.
        ///Don&apos;t close or minimize this page, because this will interrupt vehicle communcation!
        ///Do you want to continue? ähnelt.
        /// </summary>
        internal static string TalExecutionHint {
            get {
                return ResourceManager.GetString("TalExecutionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The TAL execution has been finished successfully.
        ///Do you want to keep the backup data? ähnelt.
        /// </summary>
        internal static string TalExecutionOkMessage {
            get {
                return ResourceManager.GetString("TalExecutionOkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The TAL contains flash operations but flashing is disabled for safety reasons.
        ///Possibly the software is not consistent in all ECUs. ähnelt.
        /// </summary>
        internal static string TalFlashOperation {
            get {
                return ResourceManager.GetString("TalFlashOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generating TAL ... ähnelt.
        /// </summary>
        internal static string TalGenerating {
            get {
                return ResourceManager.GetString("TalGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TAL generation failed. ähnelt.
        /// </summary>
        internal static string TalGenerationFailed {
            get {
                return ResourceManager.GetString("TalGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After replacement select the replaced ECUs at the category &apos;after the exchange&apos;. ähnelt.
        /// </summary>
        internal static string TalHwDeinstallFinished {
            get {
                return ResourceManager.GetString("TalHwDeinstallFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generating individual data TAL ... ähnelt.
        /// </summary>
        internal static string TalIdrGenerating {
            get {
                return ResourceManager.GetString("TalIdrGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TAL not present. ähnelt.
        /// </summary>
        internal static string TalMissing {
            get {
                return ResourceManager.GetString("TalMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A backup of the last TAL is present.
        ///Do you want to execute the last TAL again?
        ///The last settings have to stay unmodified in this case. ähnelt.
        /// </summary>
        internal static string TalOperationContinue {
            get {
                return ResourceManager.GetString("TalOperationContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore TAL generation failed. ähnelt.
        /// </summary>
        internal static string TalRestoreGenerationFailed {
            get {
                return ResourceManager.GetString("TalRestoreGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generating restore TAL ... ähnelt.
        /// </summary>
        internal static string TalRestoreGenrating {
            get {
                return ResourceManager.GetString("TalRestoreGenrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test module data not present. ähnelt.
        /// </summary>
        internal static string TestModuleDataMissing {
            get {
                return ResourceManager.GetString("TestModuleDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test module generation failures: {0} ähnelt.
        /// </summary>
        internal static string TestModuleFailures {
            get {
                return ResourceManager.GetString("TestModuleFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test module generation not completed: {0}% ähnelt.
        /// </summary>
        internal static string TestModuleNotCompleted {
            get {
                return ResourceManager.GetString("TestModuleNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}%, Failures: {1} ähnelt.
        /// </summary>
        internal static string TestModuleProgress {
            get {
                return ResourceManager.GetString("TestModuleProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TSL updated. ähnelt.
        /// </summary>
        internal static string TslUpdated {
            get {
                return ResourceManager.GetString("TslUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TSL update failed. ähnelt.
        /// </summary>
        internal static string TslUpdateFailed {
            get {
                return ResourceManager.GetString("TslUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating vehicle data failed. ähnelt.
        /// </summary>
        internal static string UpdateVehicleDataFailed {
            get {
                return ResourceManager.GetString("UpdateVehicleDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle connected. ähnelt.
        /// </summary>
        internal static string VehicleConnected {
            get {
                return ResourceManager.GetString("VehicleConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connecting vehicle ... ähnelt.
        /// </summary>
        internal static string VehicleConnecting {
            get {
                return ResourceManager.GetString("VehicleConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle database invalid or too old. ähnelt.
        /// </summary>
        internal static string VehicleDatabaseInvalid {
            get {
                return ResourceManager.GetString("VehicleDatabaseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detecting vehicle ... ähnelt.
        /// </summary>
        internal static string VehicleDetecting {
            get {
                return ResourceManager.GetString("VehicleDetecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detecting vehicle: {0}% ähnelt.
        /// </summary>
        internal static string VehicleDetectingProgress {
            get {
                return ResourceManager.GetString("VehicleDetectingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle detection failed. ähnelt.
        /// </summary>
        internal static string VehicleDetectionFailed {
            get {
                return ResourceManager.GetString("VehicleDetectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle disconnected. ähnelt.
        /// </summary>
        internal static string VehicleDisconnected {
            get {
                return ResourceManager.GetString("VehicleDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnecting vehicle ... ähnelt.
        /// </summary>
        internal static string VehicleDisconnecting {
            get {
                return ResourceManager.GetString("VehicleDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VIN={0}, Series={1}
        ///ILevel ship={2} current={3} ähnelt.
        /// </summary>
        internal static string VehicleInfo {
            get {
                return ResourceManager.GetString("VehicleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target selector not detected. ähnelt.
        /// </summary>
        internal static string VehicleNoTargetSelector {
            get {
                return ResourceManager.GetString("VehicleNoTargetSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle not connected. ähnelt.
        /// </summary>
        internal static string VehicleNotConnected {
            get {
                return ResourceManager.GetString("VehicleNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detected vehicle series : {0}.
        ///Coding is available only for F series or higher. ähnelt.
        /// </summary>
        internal static string VehicleSeriesInvalid {
            get {
                return ResourceManager.GetString("VehicleSeriesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle series not detected. ähnelt.
        /// </summary>
        internal static string VehicleSeriesNotDetected {
            get {
                return ResourceManager.GetString("VehicleSeriesNotDetected", resourceCulture);
            }
        }
    }
}
