//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsdzClientLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PsdzClientLibrary.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Context not found. ähnelt.
        /// </summary>
        internal static string ContextMissing {
            get {
                return ResourceManager.GetString("ContextMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creating backup path failed. ähnelt.
        /// </summary>
        internal static string CreateBackupPathFailed {
            get {
                return ResourceManager.GetString("CreateBackupPathFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detecting installed ECUs failed. ähnelt.
        /// </summary>
        internal static string DetectInstalledEcusFailed {
            get {
                return ResourceManager.GetString("DetectInstalledEcusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: {0} ähnelt.
        /// </summary>
        internal static string ExceptionMsg {
            get {
                return ResourceManager.GetString("ExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Executing backup TAL ... ähnelt.
        /// </summary>
        internal static string ExecutingBackupTal {
            get {
                return ResourceManager.GetString("ExecutingBackupTal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Executing TAL ... ähnelt.
        /// </summary>
        internal static string ExecutingTal {
            get {
                return ResourceManager.GetString("ExecutingTal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Executing operation ... ähnelt.
        /// </summary>
        internal static string ExecutingVehicleFunc {
            get {
                return ResourceManager.GetString("ExecutingVehicleFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation finished. ähnelt.
        /// </summary>
        internal static string ExecutingVehicleFuncFinished {
            get {
                return ResourceManager.GetString("ExecutingVehicleFuncFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FA backup write failed. ähnelt.
        /// </summary>
        internal static string FaBackupWriteFailed {
            get {
                return ResourceManager.GetString("FaBackupWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FA backup written. ähnelt.
        /// </summary>
        internal static string FaBackupWritten {
            get {
                return ResourceManager.GetString("FaBackupWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FA write failed. ähnelt.
        /// </summary>
        internal static string FaWriteFailed {
            get {
                return ResourceManager.GetString("FaWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FA written. ähnelt.
        /// </summary>
        internal static string FaWritten {
            get {
                return ResourceManager.GetString("FaWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service host started. ähnelt.
        /// </summary>
        internal static string HostStarted {
            get {
                return ResourceManager.GetString("HostStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting host failed. ähnelt.
        /// </summary>
        internal static string HostStartFailed {
            get {
                return ResourceManager.GetString("HostStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting service host ... ähnelt.
        /// </summary>
        internal static string HostStarting {
            get {
                return ResourceManager.GetString("HostStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service host stopped. ähnelt.
        /// </summary>
        internal static string HostStopped {
            get {
                return ResourceManager.GetString("HostStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopping service host ... ähnelt.
        /// </summary>
        internal static string HostStopping {
            get {
                return ResourceManager.GetString("HostStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ILevel backup failed. ähnelt.
        /// </summary>
        internal static string ILevelBackupFailed {
            get {
                return ResourceManager.GetString("ILevelBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ILevel backup updated. ähnelt.
        /// </summary>
        internal static string ILevelBackupUpdated {
            get {
                return ResourceManager.GetString("ILevelBackupUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ILevel updated. ähnelt.
        /// </summary>
        internal static string ILevelUpdated {
            get {
                return ResourceManager.GetString("ILevelUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ILevel update failed. ähnelt.
        /// </summary>
        internal static string ILevelUpdateFailed {
            get {
                return ResourceManager.GetString("ILevelUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detected Ncd failures. ähnelt.
        /// </summary>
        internal static string NcdFailures {
            get {
                return ResourceManager.GetString("NcdFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NCD online calculation required. ähnelt.
        /// </summary>
        internal static string NcdOnlineCalculation {
            get {
                return ResourceManager.GetString("NcdOnlineCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NCD request file missing. ähnelt.
        /// </summary>
        internal static string NoNcdRequestFile {
            get {
                return ResourceManager.GetString("NoNcdRequestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No target ILevel present. ähnelt.
        /// </summary>
        internal static string NoTargetILevel {
            get {
                return ResourceManager.GetString("NoTargetILevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PIA master updated. ähnelt.
        /// </summary>
        internal static string PiaMasterUpdated {
            get {
                return ResourceManager.GetString("PiaMasterUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PIA master update failed. ähnelt.
        /// </summary>
        internal static string PiaMasterUpdateFailed {
            get {
                return ResourceManager.GetString("PiaMasterUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reading ILevel failed. ähnelt.
        /// </summary>
        internal static string ReadILevelFailed {
            get {
                return ResourceManager.GetString("ReadILevelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reading VIN failed. ähnelt.
        /// </summary>
        internal static string ReadVinFailed {
            get {
                return ResourceManager.GetString("ReadVinFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requesting ECU context failed. ähnelt.
        /// </summary>
        internal static string RequestEcuContextFailed {
            get {
                return ResourceManager.GetString("RequestEcuContextFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detected software failures. ähnelt.
        /// </summary>
        internal static string SoftwareFailures {
            get {
                return ResourceManager.GetString("SoftwareFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generating backup TAL ... ähnelt.
        /// </summary>
        internal static string TalBackupGenerating {
            get {
                return ResourceManager.GetString("TalBackupGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup TAL generation failed. ähnelt.
        /// </summary>
        internal static string TalBackupGenerationFailed {
            get {
                return ResourceManager.GetString("TalBackupGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TAL execution finished with errors. ähnelt.
        /// </summary>
        internal static string TalExecuteError {
            get {
                return ResourceManager.GetString("TalExecuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TAL execution finished ok. ähnelt.
        /// </summary>
        internal static string TalExecuteOk {
            get {
                return ResourceManager.GetString("TalExecuteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TAL generation failed. ähnelt.
        /// </summary>
        internal static string TalGenerationFailed {
            get {
                return ResourceManager.GetString("TalGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generating TAL ... ähnelt.
        /// </summary>
        internal static string TalGenrating {
            get {
                return ResourceManager.GetString("TalGenrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TAL not present. ähnelt.
        /// </summary>
        internal static string TalMissing {
            get {
                return ResourceManager.GetString("TalMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore TAL generation failed. ähnelt.
        /// </summary>
        internal static string TalRestoreGenerationFailed {
            get {
                return ResourceManager.GetString("TalRestoreGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generating restore TAL ... ähnelt.
        /// </summary>
        internal static string TalRestoreGenrating {
            get {
                return ResourceManager.GetString("TalRestoreGenrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TSL updated. ähnelt.
        /// </summary>
        internal static string TslUpdated {
            get {
                return ResourceManager.GetString("TslUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TSL update failed. ähnelt.
        /// </summary>
        internal static string TslUpdateFailed {
            get {
                return ResourceManager.GetString("TslUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating vehicle data failed. ähnelt.
        /// </summary>
        internal static string UpdateVehicleDataFailed {
            get {
                return ResourceManager.GetString("UpdateVehicleDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle connected. ähnelt.
        /// </summary>
        internal static string VehicleConnected {
            get {
                return ResourceManager.GetString("VehicleConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connecting vehicle ... ähnelt.
        /// </summary>
        internal static string VehicleConnecting {
            get {
                return ResourceManager.GetString("VehicleConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detecting vehicle ... ähnelt.
        /// </summary>
        internal static string VehicleDetecting {
            get {
                return ResourceManager.GetString("VehicleDetecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle detection failed. ähnelt.
        /// </summary>
        internal static string VehicleDetectionFailed {
            get {
                return ResourceManager.GetString("VehicleDetectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle disconnected. ähnelt.
        /// </summary>
        internal static string VehicleDisconnected {
            get {
                return ResourceManager.GetString("VehicleDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnecting vehicle ... ähnelt.
        /// </summary>
        internal static string VehicleDisconnecting {
            get {
                return ResourceManager.GetString("VehicleDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VIN={0}, Series={1}
        ///ILevel ship={2} current={3} ähnelt.
        /// </summary>
        internal static string VehicleInfo {
            get {
                return ResourceManager.GetString("VehicleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target selector not detected. ähnelt.
        /// </summary>
        internal static string VehicleNoTargetSelector {
            get {
                return ResourceManager.GetString("VehicleNoTargetSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle not connected. ähnelt.
        /// </summary>
        internal static string VehicleNotConnected {
            get {
                return ResourceManager.GetString("VehicleNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle series not detected. ähnelt.
        /// </summary>
        internal static string VehicleSeriesNotDetected {
            get {
                return ResourceManager.GetString("VehicleSeriesNotDetected", resourceCulture);
            }
        }
    }
}
