//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.8000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarControl.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarControl.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conveyor ähnelt.
        /// </summary>
        internal static string axisModeConveyor {
            get {
                return ResourceManager.GetString("axisModeConveyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Garage ähnelt.
        /// </summary>
        internal static string axisModeGarage {
            get {
                return ResourceManager.GetString("axisModeGarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        /// </summary>
        internal static string axisModeNormal {
            get {
                return ResourceManager.GetString("axisModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transport ähnelt.
        /// </summary>
        internal static string axisModeTransport {
            get {
                return ResourceManager.GetString("axisModeTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battery ähnelt.
        /// </summary>
        internal static string batteryStatus {
            get {
                return ResourceManager.GetString("batteryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect ähnelt.
        /// </summary>
        internal static string buttonModeConnect {
            get {
                return ResourceManager.GetString("buttonModeConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnect ähnelt.
        /// </summary>
        internal static string buttonModeDisconnect {
            get {
                return ResourceManager.GetString("buttonModeDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die East ähnelt.
        /// </summary>
        internal static string cccNavDirEast {
            get {
                return ResourceManager.GetString("cccNavDirEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North ähnelt.
        /// </summary>
        internal static string cccNavDirNorth {
            get {
                return ResourceManager.GetString("cccNavDirNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South ähnelt.
        /// </summary>
        internal static string cccNavDirSouth {
            get {
                return ResourceManager.GetString("cccNavDirSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die West ähnelt.
        /// </summary>
        internal static string cccNavDirWest {
            get {
                return ResourceManager.GetString("cccNavDirWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2D positioning ähnelt.
        /// </summary>
        internal static string cccNavGpsPos2D {
            get {
                return ResourceManager.GetString("cccNavGpsPos2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3D positioning ähnelt.
        /// </summary>
        internal static string cccNavGpsPos3D {
            get {
                return ResourceManager.GetString("cccNavGpsPos3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        internal static string cccNavGpsPosSearch {
            get {
                return ResourceManager.GetString("cccNavGpsPosSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tracking ähnelt.
        /// </summary>
        internal static string cccNavGpsPosTrack {
            get {
                return ResourceManager.GetString("cccNavGpsPosTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value below threshold ähnelt.
        /// </summary>
        internal static string errorClassBelowThreshold {
            get {
                return ResourceManager.GetString("errorClassBelowThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid signal ähnelt.
        /// </summary>
        internal static string errorClassInvalidValue {
            get {
                return ResourceManager.GetString("errorClassInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No error symptom ähnelt.
        /// </summary>
        internal static string errorClassNoSymptom {
            get {
                return ResourceManager.GetString("errorClassNoSymptom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No signal ähnelt.
        /// </summary>
        internal static string errorClassNoValue {
            get {
                return ResourceManager.GetString("errorClassNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value over threshold ähnelt.
        /// </summary>
        internal static string errorClassOverThreshold {
            get {
                return ResourceManager.GetString("errorClassOverThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error unknown ähnelt.
        /// </summary>
        internal static string errorClassUnknown {
            get {
                return ResourceManager.GetString("errorClassUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ACSM Crash security module ähnelt.
        /// </summary>
        internal static string errorNameACSM {
            get {
                return ResourceManager.GetString("errorNameACSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AHM Trailer module ähnelt.
        /// </summary>
        internal static string errorNameAHM {
            get {
                return ResourceManager.GetString("errorNameAHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAS Car access system ähnelt.
        /// </summary>
        internal static string errorNameCAS {
            get {
                return ResourceManager.GetString("errorNameCAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CCC-A Applications ähnelt.
        /// </summary>
        internal static string errorNameCCCA {
            get {
                return ResourceManager.GetString("errorNameCCCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CCC-ANT Antenna tuner ähnelt.
        /// </summary>
        internal static string errorNameCCCANT {
            get {
                return ResourceManager.GetString("errorNameCCCANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CCC-ASK Audio system controller ähnelt.
        /// </summary>
        internal static string errorNameCCCASK {
            get {
                return ResourceManager.GetString("errorNameCCCASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CCC-BO Front panel ähnelt.
        /// </summary>
        internal static string errorNameCCCBO {
            get {
                return ResourceManager.GetString("errorNameCCCBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CCC-GW Gateway ähnelt.
        /// </summary>
        internal static string errorNameCCCGW {
            get {
                return ResourceManager.GetString("errorNameCCCGW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CDC CD disk charger ähnelt.
        /// </summary>
        internal static string errorNameCDC {
            get {
                return ResourceManager.GetString("errorNameCDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CID Central information display ähnelt.
        /// </summary>
        internal static string errorNameCID {
            get {
                return ResourceManager.GetString("errorNameCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CON Controller ähnelt.
        /// </summary>
        internal static string errorNameCON {
            get {
                return ResourceManager.GetString("errorNameCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DDE Diesel elektronic ähnelt.
        /// </summary>
        internal static string errorNameDDE {
            get {
                return ResourceManager.GetString("errorNameDDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DSC Dynamic stability control ähnelt.
        /// </summary>
        internal static string errorNameDSC {
            get {
                return ResourceManager.GetString("errorNameDSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EHC Level control ähnelt.
        /// </summary>
        internal static string errorNameEHC {
            get {
                return ResourceManager.GetString("errorNameEHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EKPS Fuel pump control ähnelt.
        /// </summary>
        internal static string errorNameEKPS {
            get {
                return ResourceManager.GetString("errorNameEKPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IHK Integrated heating climate automatic ähnelt.
        /// </summary>
        internal static string errorNameIHK {
            get {
                return ResourceManager.GetString("errorNameIHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KBM Chassis basic module ähnelt.
        /// </summary>
        internal static string errorNameKBM {
            get {
                return ResourceManager.GetString("errorNameKBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KGM Chassis gateway module ähnelt.
        /// </summary>
        internal static string errorNameKGM {
            get {
                return ResourceManager.GetString("errorNameKGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KOMBI Combination instrument ähnelt.
        /// </summary>
        internal static string errorNameKOMBI {
            get {
                return ResourceManager.GetString("errorNameKOMBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LM Light module ähnelt.
        /// </summary>
        internal static string errorNameLM {
            get {
                return ResourceManager.GetString("errorNameLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDC Park distance control ähnelt.
        /// </summary>
        internal static string errorNamePDC {
            get {
                return ResourceManager.GetString("errorNamePDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RLS Rain main beam sensor ähnelt.
        /// </summary>
        internal static string errorNameRLS {
            get {
                return ResourceManager.GetString("errorNameRLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SZL Gearshift unit steering column ähnelt.
        /// </summary>
        internal static string errorNameSZL {
            get {
                return ResourceManager.GetString("errorNameSZL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SZM Gearshift unit center console ähnelt.
        /// </summary>
        internal static string errorNameSZM {
            get {
                return ResourceManager.GetString("errorNameSZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TCU Telematic control unit ähnelt.
        /// </summary>
        internal static string errorNameTCU {
            get {
                return ResourceManager.GetString("errorNameTCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No errors present ähnelt.
        /// </summary>
        internal static string errorNoError {
            get {
                return ResourceManager.GetString("errorNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No response ähnelt.
        /// </summary>
        internal static string errorNoResponse {
            get {
                return ResourceManager.GetString("errorNoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error never occured ähnelt.
        /// </summary>
        internal static string errorPresentNever {
            get {
                return ResourceManager.GetString("errorPresentNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error not present ähnelt.
        /// </summary>
        internal static string errorPresentNotNow {
            get {
                return ResourceManager.GetString("errorPresentNotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error present ähnelt.
        /// </summary>
        internal static string errorPresentNow {
            get {
                return ResourceManager.GetString("errorPresentNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning lamp ähnelt.
        /// </summary>
        internal static string errorWarningActive {
            get {
                return ResourceManager.GetString("errorWarningActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Store log ähnelt.
        /// </summary>
        internal static string storeLog {
            get {
                return ResourceManager.GetString("storeLog", resourceCulture);
            }
        }
    }
}
