<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFrameworks>net10.0-windows10.0.26100.0;net481</TargetFrameworks>
      <ImplicitUsings>disable</ImplicitUsings>
      <Nullable>disable</Nullable>
      <Platforms>AnyCPU</Platforms>
      <PlatformTarget>AnyCPU</PlatformTarget>
      <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows10.0.26100.0|AnyCPU'">
    <NoWarn>CS0219;CS0162;CS1717;CS0618</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net481|AnyCPU'">
    <NoWarn>CS0219;CS0162;CS1717;CS0618</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows10.0.26100.0|AnyCPU'">
    <NoWarn>CS0219;CS0162;CS1717;CS0618</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net481|AnyCPU'">
    <NoWarn>CS0219;CS0162;CS1717;CS0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PsdzClientLibrary\PsdzClientLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Source\ABL_GEN_*.cs" />
    <Compile Remove="..\Source\ABL_GEN_AG*.cs" />
    <Compile Remove="..\Source\ABL_GEN_AT*.cs" />
    <Compile Remove="..\Source\ABL_GEN_AU*.cs" />
    <Compile Remove="..\Source\ABL_GEN_G*.cs" />
    <Compile Remove="..\Source\ABL_GEN_G*.cs" />
    <Compile Remove="..\Source\ABL_GEN_BIKE_SET_SERVICEDATA*" />
    <Compile Remove="..\Source\ABL_GEN_LIB_BIKE_UXP_COMPLETECODING.cs" />
    <Compile Remove="..\Source\ABL_GEN_RESTOREINDIVDATA.cs" />
  </ItemGroup>

</Project>
