#!/bin/sh
uci set system.@system[0].hostname='DeepObdBMW'
uci set system.led_wifi=led
uci set system.led_wifi.default='0'
uci set system.led_wifi.name='WIFI'
uci set system.led_wifi.sysfs='a5-v11:blue:system'
uci set system.led_wifi.trigger='netdev'
uci set system.led_wifi.dev='wlan0'
uci set system.led_wifi.mode='link tx rx'
uci commit system
exit 0
