#!/bin/sh
uci set wireless.radio0.disabled=''
uci set wireless.@wifi-iface[0].mode='ap'
uci set wireless.@wifi-iface[0].encryption='psk2'
uci set wireless.@wifi-iface[0].key='deepobdbmw'
uci set wireless.@wifi-iface[0].ssid='Deep OBD BMW'
uci set wireless.@wifi-iface[0].disassoc_low_ack='1'
uci commit wireless
exit 0
