using BMW.Rheingold.Psdz.Model.Certificate;
using System.Collections.Generic;

namespace BMW.Rheingold.Psdz
{
    internal class SecurityCalculationDetailedStatusEtoMapper : MapperBase<PsdzCertCalculationDetailedStatus, SecurityCalculationDetailedStatusEto>
    {
        protected override IDictionary<PsdzCertCalculationDetailedStatus, SecurityCalculationDetailedStatusEto> CreateMap()
        {
            return new Dictionary<PsdzCertCalculationDetailedStatus, SecurityCalculationDetailedStatusEto>
        {
            {
                PsdzCertCalculationDetailedStatus.CertDenied,
                SecurityCalculationDetailedStatusEto.CERT_DENIED
            },
            {
                PsdzCertCalculationDetailedStatus.CnameDenied,
                SecurityCalculationDetailedStatusEto.CNAME_DENIED
            },
            {
                PsdzCertCalculationDetailedStatus.CnameMissing,
                SecurityCalculationDetailedStatusEto.CNAME_MISSING
            },
            {
                PsdzCertCalculationDetailedStatus.EcuNameDenied,
                SecurityCalculationDetailedStatusEto.ECU_NAME_DENIED
            },
            {
                PsdzCertCalculationDetailedStatus.EcuNameMissing,
                SecurityCalculationDetailedStatusEto.ECU_NAME_MISSING
            },
            {
                PsdzCertCalculationDetailedStatus.EcuUidDenied,
                SecurityCalculationDetailedStatusEto.ECU_UID_DENIED
            },
            {
                PsdzCertCalculationDetailedStatus.EcuUidFormat,
                SecurityCalculationDetailedStatusEto.ECU_UID_FORMAT
            },
            {
                PsdzCertCalculationDetailedStatus.EcuUidMismatch,
                SecurityCalculationDetailedStatusEto.ECU_UID_MISMATCH
            },
            {
                PsdzCertCalculationDetailedStatus.EcuUidMissing,
                SecurityCalculationDetailedStatusEto.ECU_UID_MISSING
            },
            {
                PsdzCertCalculationDetailedStatus.Error,
                SecurityCalculationDetailedStatusEto.ERROR
            },
            {
                PsdzCertCalculationDetailedStatus.Malformed,
                SecurityCalculationDetailedStatusEto.MALFORMED
            },
            {
                PsdzCertCalculationDetailedStatus.Ok,
                SecurityCalculationDetailedStatusEto.OK
            },
            {
                PsdzCertCalculationDetailedStatus.CaError,
                SecurityCalculationDetailedStatusEto.CA_ERROR
            },
            {
                PsdzCertCalculationDetailedStatus.EcuDenied,
                SecurityCalculationDetailedStatusEto.ECU_DENIED
            },
            {
                PsdzCertCalculationDetailedStatus.KeyIdUnknown,
                SecurityCalculationDetailedStatusEto.KEYID_UNKNOWN
            },
            {
                PsdzCertCalculationDetailedStatus.KeyIdDenied,
                SecurityCalculationDetailedStatusEto.KEYID_DENIED
            }
        };
        }
    }
}