using System.Collections.Generic;
using BMW.Rheingold.Psdz.Model.Tal;

namespace BMW.Rheingold.Psdz
{
    internal class TaCategoryTypeMapper : MapperBase<PsdzTaCategories, TACategories>
    {
        protected override IDictionary<PsdzTaCategories, TACategories> CreateMap()
        {
            return new Dictionary<PsdzTaCategories, TACategories>
            {
                {
                    PsdzTaCategories.BlFlash,
                    TACategories.BL_FLASH
                },
                {
                    PsdzTaCategories.CdDeploy,
                    TACategories.CD_DEPLOY
                },
                {
                    PsdzTaCategories.FscBackup,
                    TACategories.FSC_BACKUP
                },
                {
                    PsdzTaCategories.FscDeploy,
                    TACategories.FSC_DEPLOY
                },
                {
                    PsdzTaCategories.FscDeployPrehwd,
                    TACategories.FSC_DEPLOY_PREHWD
                },
                {
                    PsdzTaCategories.GatewayTableDeploy,
                    TACategories.GATEWAY_TABLE_DEPLOY
                },
                {
                    PsdzTaCategories.HddUpdate,
                    TACategories.HDD_UPDATE
                },
                {
                    PsdzTaCategories.HwDeinstall,
                    TACategories.HW_DEINSTALL
                },
                {
                    PsdzTaCategories.HwInstall,
                    TACategories.HW_INSTALL
                },
                {
                    PsdzTaCategories.IbaDeploy,
                    TACategories.IBA_DEPLOY
                },
                {
                    PsdzTaCategories.IdBackup,
                    TACategories.ID_BACKUP
                },
                {
                    PsdzTaCategories.IdRestore,
                    TACategories.ID_RESTORE
                },
                {
                    PsdzTaCategories.SwDeploy,
                    TACategories.SW_DEPLOY
                },
                {
                    PsdzTaCategories.SFADeploy,
                    TACategories.SFA_DEPLOY
                },
                {
                    PsdzTaCategories.Unknown,
                    TACategories.UNKNOWN
                },
                {
                    PsdzTaCategories.EcuActivate,
                    TACategories.ECU_ACTIVATE
                },
                {
                    PsdzTaCategories.EcuPoll,
                    TACategories.ECU_POLL
                },
                {
                    PsdzTaCategories.EcuMirrorDeploy,
                    TACategories.ECU_MIRROR_DEPLOY
                },
                {
                    PsdzTaCategories.SmacTransferStart,
                    TACategories.SMAC_TRANSFER_START
                },
                {
                    PsdzTaCategories.SmacTransferStatus,
                    TACategories.SMAC_TRANSFER_STATUS
                }
            };
        }
    }
}