using BMW.Rheingold.Psdz.Model.Sfa;
using System.Collections.Generic;

namespace BMW.Rheingold.Psdz
{
    internal class TokenDetailedStatusEtoMapper : MapperBase<PsdzTokenDetailedStatusEtoEnum, TokenDetailedStatusEto>
    {
        protected override IDictionary<PsdzTokenDetailedStatusEtoEnum, TokenDetailedStatusEto> CreateMap()
        {
            return new Dictionary<PsdzTokenDetailedStatusEtoEnum, TokenDetailedStatusEto>
            {
                {
                    PsdzTokenDetailedStatusEtoEnum.OK,
                    TokenDetailedStatusEto.OK
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.ERROR,
                    TokenDetailedStatusEto.ERROR
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.MALFORMED,
                    TokenDetailedStatusEto.MALFORMED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.LINKTOID_FORMAT,
                    TokenDetailedStatusEto.LINKTOID_FORMAT
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.LINKTOID_MISSING,
                    TokenDetailedStatusEto.LINKTOID_MISSING
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.LINKTOID_MISMATCH,
                    TokenDetailedStatusEto.LINKTOID_MISMATCH
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.LINKTOID_DENIED,
                    TokenDetailedStatusEto.LINKTOID_DENIED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.LINKTOIDTYPE_DENIED,
                    TokenDetailedStatusEto.LINKTOIDTYPE_DENIED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.VIN_MISSING,
                    TokenDetailedStatusEto.VIN_MISSING
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.VIN_DENIED,
                    TokenDetailedStatusEto.VIN_DENIED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.FEATUREID_MISSING,
                    TokenDetailedStatusEto.FEATUREID_MISSING
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.FEATUREID_DENIED,
                    TokenDetailedStatusEto.FEATUREID_DENIED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.FEATUREID_UNKNOWN,
                    TokenDetailedStatusEto.FEATUREID_UNKNOWN
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.TOKENPACKAGEREFERENCE_DENIED,
                    TokenDetailedStatusEto.TOKENPACKAGEREFERENCE_DENIED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.TOKENPACKAGEREFERENCE_UNKNOWN,
                    TokenDetailedStatusEto.TOKENPACKAGEREFERENCE_UNKNOWN
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.TOKENPACKAGEREFERENCE_MISSMATCH,
                    TokenDetailedStatusEto.TOKENPACKAGEREFERENCE_MISSMATCH
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.TOKENPACKAGE_REBUILD_ERROR,
                    TokenDetailedStatusEto.TOKENPACKAGE_REBUILD_ERROR
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.VIN_MALFORMED,
                    TokenDetailedStatusEto.VIN_MALFORMED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.NOT_A_DEVELOPMENT_VIN,
                    TokenDetailedStatusEto.NOT_A_DEVELOPMENT_VIN
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.NOT_A_CUSTOMER_VIN,
                    TokenDetailedStatusEto.NOT_A_CUSTOMER_VIN
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.ECU_UID_DENIED,
                    TokenDetailedStatusEto.ECU_UID_DENIED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.NOT_A_DEVELOPMENT_ECU_UID,
                    TokenDetailedStatusEto.NOT_A_DEVELOPMENT_ECU_UID
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.NOT_A_CUSTOMER_ECU_UID,
                    TokenDetailedStatusEto.NOT_A_CUSTOMER_ECU_UID
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.ECU_UID_MALFORMED,
                    TokenDetailedStatusEto.ECU_UID_MALFORMED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.ECU_UID_PREFIX_INVALID,
                    TokenDetailedStatusEto.ECU_UID_PREFIX_INVALID
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.FEATUREID_NOT_ALLOWED,
                    TokenDetailedStatusEto.FEATUREID_NOT_ALLOWED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.FEATUREID_MALFORMED,
                    TokenDetailedStatusEto.FEATUREID_MALFORMED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.NO_VALIDITY_CONDITION_ALLOWED,
                    TokenDetailedStatusEto.NO_VALIDITY_CONDITION_ALLOWED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.VALIDITY_CONDITION_TYPE_DENIED,
                    TokenDetailedStatusEto.VALIDITY_CONDITION_TYPE_DENIED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.VALIDITY_CONDITION_TYPE_UNKNOWN,
                    TokenDetailedStatusEto.VALIDITY_CONDITION_TYPE_UNKNOWN
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.VALIDITY_CONDITION_VALUE_NOT_ALLOWED,
                    TokenDetailedStatusEto.VALIDITY_CONDITION_VALUE_NOT_ALLOWED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.VALIDITY_CONDITION_VALUE_MALFORMED,
                    TokenDetailedStatusEto.VALIDITY_CONDITION_VALUE_MALFORMED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.NO_ENABLE_TYPE_ALLOWED,
                    TokenDetailedStatusEto.NO_ENABLE_TYPE_ALLOWED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.ENABLE_TYPE_NOT_ALLOWED,
                    TokenDetailedStatusEto.ENABLE_TYPE_NOT_ALLOWED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.ENABLE_TYPE_UNKNOWN,
                    TokenDetailedStatusEto.ENABLE_TYPE_UNKNOWN
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.NO_FEATURE_SPECIFIC_FIELD_ALLOWED,
                    TokenDetailedStatusEto.NO_FEATURE_SPECIFIC_FIELD_ALLOWED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.FEATURE_SPECIFIC_FIELD_TYPE_NOT_ALLOWED,
                    TokenDetailedStatusEto.FEATURE_SPECIFIC_FIELD_TYPE_NOT_ALLOWED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.FEATURE_SPECIFIC_FIELD_TYPE_UNKNOWN,
                    TokenDetailedStatusEto.FEATURE_SPECIFIC_FIELD_TYPE_UNKNOWN
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.FEATURE_SPECIFIC_FIELD_VALUE_NOT_ALLOWED,
                    TokenDetailedStatusEto.FEATURE_SPECIFIC_FIELD_VALUE_NOT_ALLOWED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.FEATURE_SPECIFIC_FIELD_VALUE_MALFORMED,
                    TokenDetailedStatusEto.FEATURE_SPECIFIC_FIELD_VALUE_MALFORMED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.FEATURE_SET_REFERENCE_DENIED,
                    TokenDetailedStatusEto.FEATURE_SET_REFERENCE_DENIED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.FEATURE_SET_REFERENCE_UNKNOWN,
                    TokenDetailedStatusEto.FEATURE_SET_REFERENCE_UNKNOWN
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.FEATURE_SET_REFERENCE_MISSMATCH,
                    TokenDetailedStatusEto.FEATURE_SET_REFERENCE_MISSMATCH
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.FEATURE_SET_REFERENCE_REBUILD_ERROR,
                    TokenDetailedStatusEto.FEATURE_SET_REFERENCE_REBUILD_ERROR
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.REBUILD_ERROR,
                    TokenDetailedStatusEto.REBUILD_ERROR
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.DIAGNOSTIC_ADDRESS_MALFORMED,
                    TokenDetailedStatusEto.DIAGNOSTIC_ADDRESS_MALFORMED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.E_VALIDITY_CONDITION_TAG_DUPLICATE,
                    TokenDetailedStatusEto.E_VALIDITY_CONDITION_TAG_DUPLICATE
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.E_FEATURE_SPECIFIC_FIELD_TAG_DUPLICATE,
                    TokenDetailedStatusEto.E_FEATURE_SPECIFIC_FIELD_TAG_DUPLICATE
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.E_NO_RIGHTS_ASSIGNED,
                    TokenDetailedStatusEto.E_NO_RIGHTS_ASSIGNED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.E_ECU_UID_PREFIX_NOT_ALLOWED,
                    TokenDetailedStatusEto.E_ECU_UID_PREFIX_NOT_ALLOWED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.E_KDS_CLIENT_NOT_ALLOWED,
                    TokenDetailedStatusEto.E_KDS_CLIENT_NOT_ALLOWED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.E_KDS_ZSG_NOT_ALLOWED,
                    TokenDetailedStatusEto.E_KDS_ZSG_NOT_ALLOWED
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.E_UNAUTHORIZED_DOWNGRADE,
                    TokenDetailedStatusEto.E_UNAUTHORIZED_DOWNGRADE
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.E_NO_ENTRIES_IN_FSF,
                    TokenDetailedStatusEto.E_NO_ENTRIES_IN_FSF
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.E_INVALID_ENTRY_IN_FSF,
                    TokenDetailedStatusEto.E_INVALID_ENTRY_IN_FSF
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.E_DUPLICATE_TOKEN_REQUEST,
                    TokenDetailedStatusEto.E_DUPLICATE_TOKEN_REQUEST
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.E_UPGRADE_INDEX_EXCEEDS_THRESHOLD,
                    TokenDetailedStatusEto.E_UPGRADE_INDEX_EXCEEDS_THRESHOLD
                },
                {
                    PsdzTokenDetailedStatusEtoEnum.UNDEFINED,
                    TokenDetailedStatusEto.UNDEFINED
                }
            };
        }
    }
}